$axure.loadCurrentPage({
  "url":"历史成绩.html",
  "generationDate":new Date(1503559313663.19),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"85ede963ac244f4990f91ae7eb4b025a",
    "type":"Axure:Page",
    "name":"历史成绩",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4a4e8608f4e041b9b25ae5beb453b375",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":750,
              "height":1334}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fa74eefc8a2463db5473e4c5d198b2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":750,
                  "height":1334}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史成绩/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "4a4e8608f4e041b9b25ae5beb453b375":{
      "scriptId":"u0"},
    "2fa74eefc8a2463db5473e4c5d198b2f":{
      "scriptId":"u1"}}});