$axure.loadCurrentPage({
  "url":"驾考在线学习.html",
  "generationDate":new Date(1503559313532.18),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"60069527f48b46dd8120dfb1728599a4",
    "type":"Axure:Page",
    "name":"驾考在线学习",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"31077f23cc9f4264a2184459ad235dab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":647}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8453183bce5241edb787eb6cc6bfe8cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":647}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/驾考在线学习/u0.png"}},
{
          "id":"2b1d07563a564a6c88c4161cb0b6c5bc",
          "label":"模拟考试1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":20,
              "y":70},
            "size":{
              "width":340,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ef3f4fc42f748faaa62614c2337a3da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":20,
                  "y":70},
                "size":{
                  "width":340,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/驾考在线学习/模拟考试1_u2.png"}},
{
          "id":"5d38d79ce39e4463b9bf7076a8b09a70",
          "label":"模拟考试2",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":18,
              "y":180},
            "size":{
              "width":340,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2964f763f614c7daa4139b4b6429b85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":18,
                  "y":180},
                "size":{
                  "width":340,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/驾考在线学习/模拟考试1_u2.png"}},
{
          "id":"20e6104f20be4ed991edb3892e0b6f3a",
          "label":"历史成绩",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":18,
              "y":290},
            "size":{
              "width":340,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21a63e1986c94704b21965e3af6a38ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":18,
                  "y":290},
                "size":{
                  "width":340,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/驾考在线学习/模拟考试1_u2.png"}},
{
          "id":"bdef0fef6b234834b54c7d321f825963",
          "label":"我的错题",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":18,
              "y":390},
            "size":{
              "width":340,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"367ad80e27c644298335de44d0e72cf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":18,
                  "y":390},
                "size":{
                  "width":340,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/驾考在线学习/模拟考试1_u2.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "31077f23cc9f4264a2184459ad235dab":{
      "scriptId":"u0"},
    "8453183bce5241edb787eb6cc6bfe8cd":{
      "scriptId":"u1"},
    "2b1d07563a564a6c88c4161cb0b6c5bc":{
      "scriptId":"u2"},
    "2ef3f4fc42f748faaa62614c2337a3da":{
      "scriptId":"u3"},
    "5d38d79ce39e4463b9bf7076a8b09a70":{
      "scriptId":"u4"},
    "a2964f763f614c7daa4139b4b6429b85":{
      "scriptId":"u5"},
    "20e6104f20be4ed991edb3892e0b6f3a":{
      "scriptId":"u6"},
    "21a63e1986c94704b21965e3af6a38ee":{
      "scriptId":"u7"},
    "bdef0fef6b234834b54c7d321f825963":{
      "scriptId":"u8"},
    "367ad80e27c644298335de44d0e72cf8":{
      "scriptId":"u9"}}});